/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FindAccountRouteImport } from './routes/find-account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTasksRouteImport } from './routes/dashboard.tasks'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardLeadershipRouteImport } from './routes/dashboard.leadership'
import { Route as DashboardInviteesRouteImport } from './routes/dashboard.invitees'
import { Route as DashboardHelpRouteImport } from './routes/dashboard.help'
import { Route as DashboardGroupsRouteImport } from './routes/dashboard.groups'
import { Route as DashboardGivingRouteImport } from './routes/dashboard.giving'
import { Route as DashboardCellsRouteImport } from './routes/dashboard.cells'
import { Route as DashboardMembersIndexRouteImport } from './routes/dashboard.members.index'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard.events.index'
import { Route as DashboardChurchIndexRouteImport } from './routes/dashboard.church.index'
import { Route as DashboardMembersIdRouteImport } from './routes/dashboard.members.$id'
import { Route as DashboardEventsIdRouteImport } from './routes/dashboard.events.$id'
import { Route as DashboardChurchIdRouteImport } from './routes/dashboard.church.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FindAccountRoute = FindAccountRouteImport.update({
  id: '/find-account',
  path: '/find-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadershipRoute = DashboardLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInviteesRoute = DashboardInviteesRouteImport.update({
  id: '/invitees',
  path: '/invitees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsRoute = DashboardGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGivingRoute = DashboardGivingRouteImport.update({
  id: '/giving',
  path: '/giving',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCellsRoute = DashboardCellsRouteImport.update({
  id: '/cells',
  path: '/cells',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersIndexRoute = DashboardMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChurchIndexRoute = DashboardChurchIndexRouteImport.update({
  id: '/church/',
  path: '/church/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersIdRoute = DashboardMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIdRoute = DashboardEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChurchIdRoute = DashboardChurchIdRouteImport.update({
  id: '/church/$id',
  path: '/church/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/find-account': typeof FindAccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/cells': typeof DashboardCellsRoute
  '/dashboard/giving': typeof DashboardGivingRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/invitees': typeof DashboardInviteesRoute
  '/dashboard/leadership': typeof DashboardLeadershipRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/church/$id': typeof DashboardChurchIdRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/members/$id': typeof DashboardMembersIdRoute
  '/dashboard/church/': typeof DashboardChurchIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/members/': typeof DashboardMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-account': typeof FindAccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/cells': typeof DashboardCellsRoute
  '/dashboard/giving': typeof DashboardGivingRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/invitees': typeof DashboardInviteesRoute
  '/dashboard/leadership': typeof DashboardLeadershipRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/church/$id': typeof DashboardChurchIdRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/members/$id': typeof DashboardMembersIdRoute
  '/dashboard/church': typeof DashboardChurchIndexRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/members': typeof DashboardMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/find-account': typeof FindAccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/cells': typeof DashboardCellsRoute
  '/dashboard/giving': typeof DashboardGivingRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/invitees': typeof DashboardInviteesRoute
  '/dashboard/leadership': typeof DashboardLeadershipRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/church/$id': typeof DashboardChurchIdRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/members/$id': typeof DashboardMembersIdRoute
  '/dashboard/church/': typeof DashboardChurchIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/members/': typeof DashboardMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/find-account'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/cells'
    | '/dashboard/giving'
    | '/dashboard/groups'
    | '/dashboard/help'
    | '/dashboard/invitees'
    | '/dashboard/leadership'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/'
    | '/dashboard/church/$id'
    | '/dashboard/events/$id'
    | '/dashboard/members/$id'
    | '/dashboard/church/'
    | '/dashboard/events/'
    | '/dashboard/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/find-account'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/cells'
    | '/dashboard/giving'
    | '/dashboard/groups'
    | '/dashboard/help'
    | '/dashboard/invitees'
    | '/dashboard/leadership'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard'
    | '/dashboard/church/$id'
    | '/dashboard/events/$id'
    | '/dashboard/members/$id'
    | '/dashboard/church'
    | '/dashboard/events'
    | '/dashboard/members'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/find-account'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/cells'
    | '/dashboard/giving'
    | '/dashboard/groups'
    | '/dashboard/help'
    | '/dashboard/invitees'
    | '/dashboard/leadership'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/'
    | '/dashboard/church/$id'
    | '/dashboard/events/$id'
    | '/dashboard/members/$id'
    | '/dashboard/church/'
    | '/dashboard/events/'
    | '/dashboard/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FindAccountRoute: typeof FindAccountRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-account': {
      id: '/find-account'
      path: '/find-account'
      fullPath: '/find-account'
      preLoaderRoute: typeof FindAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leadership': {
      id: '/dashboard/leadership'
      path: '/leadership'
      fullPath: '/dashboard/leadership'
      preLoaderRoute: typeof DashboardLeadershipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invitees': {
      id: '/dashboard/invitees'
      path: '/invitees'
      fullPath: '/dashboard/invitees'
      preLoaderRoute: typeof DashboardInviteesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups': {
      id: '/dashboard/groups'
      path: '/groups'
      fullPath: '/dashboard/groups'
      preLoaderRoute: typeof DashboardGroupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/giving': {
      id: '/dashboard/giving'
      path: '/giving'
      fullPath: '/dashboard/giving'
      preLoaderRoute: typeof DashboardGivingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cells': {
      id: '/dashboard/cells'
      path: '/cells'
      fullPath: '/dashboard/cells'
      preLoaderRoute: typeof DashboardCellsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members/': {
      id: '/dashboard/members/'
      path: '/members'
      fullPath: '/dashboard/members/'
      preLoaderRoute: typeof DashboardMembersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/church/': {
      id: '/dashboard/church/'
      path: '/church'
      fullPath: '/dashboard/church/'
      preLoaderRoute: typeof DashboardChurchIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members/$id': {
      id: '/dashboard/members/$id'
      path: '/members/$id'
      fullPath: '/dashboard/members/$id'
      preLoaderRoute: typeof DashboardMembersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/$id': {
      id: '/dashboard/events/$id'
      path: '/events/$id'
      fullPath: '/dashboard/events/$id'
      preLoaderRoute: typeof DashboardEventsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/church/$id': {
      id: '/dashboard/church/$id'
      path: '/church/$id'
      fullPath: '/dashboard/church/$id'
      preLoaderRoute: typeof DashboardChurchIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCellsRoute: typeof DashboardCellsRoute
  DashboardGivingRoute: typeof DashboardGivingRoute
  DashboardGroupsRoute: typeof DashboardGroupsRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardInviteesRoute: typeof DashboardInviteesRoute
  DashboardLeadershipRoute: typeof DashboardLeadershipRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardChurchIdRoute: typeof DashboardChurchIdRoute
  DashboardEventsIdRoute: typeof DashboardEventsIdRoute
  DashboardMembersIdRoute: typeof DashboardMembersIdRoute
  DashboardChurchIndexRoute: typeof DashboardChurchIndexRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardMembersIndexRoute: typeof DashboardMembersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCellsRoute: DashboardCellsRoute,
  DashboardGivingRoute: DashboardGivingRoute,
  DashboardGroupsRoute: DashboardGroupsRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardInviteesRoute: DashboardInviteesRoute,
  DashboardLeadershipRoute: DashboardLeadershipRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardChurchIdRoute: DashboardChurchIdRoute,
  DashboardEventsIdRoute: DashboardEventsIdRoute,
  DashboardMembersIdRoute: DashboardMembersIdRoute,
  DashboardChurchIndexRoute: DashboardChurchIndexRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardMembersIndexRoute: DashboardMembersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FindAccountRoute: FindAccountRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
